CREATE database `query`;
CREATE TABLE `user` (`Id` int, `username` varchar(256), `phone` in, `adress` ENUM('Chennai', 'pune', 'Hyderabad'));
ALTER table user MODIFY COLUMN phone INT(10);
ALTER table user rename COLUMN adress to city;
ALTER table user add COLUMN `age` INT;
ALTER table user drop COLUMN phone;
ALTER table user add COLUMN phone INT(12);
ALTER table user add COLUMN `Education` VARCHAR(256);
INSERT into user values (1, 'arun', 'pune', 20, 9123456788, 'IT');
SET SQL_SAFE_UPDATES = 0;
UPDATE user SET city = 'goa' WHERE Id = 1;
select * from user;
insert into user values (2, 'Hari', 'pune', 20 , 123456789009, 'BME');
insert into user values (3, 'ravi', 'Chennai', 20 , 46654789009, 'MECH');
select * from user WHERE Id = 1 and age = 22;
select * from user WHERE age = 22;
select sum (phone) AS contact FROM user;
SET SQL_SAFE_UPDATES = 0;
UPDATE user SET username = 'kumar' WHERE Id = 2;
select * from user order by Id;
DELETE from user  WHERE age = 22;
UPDATE user SET age = 20 WHERE age = 22;
ALTER table user drop column Education ;
select avg(age) from user;